host: tddevtest.td.teradata.com
logmech: LDAP
encrypt: False
plugin-local: teradata.py
username: sh186014
password: "as;dlkfj"
icon: appcode/plugins/dbconnections/Teradata.png
plugin: Teradata.py
plugin-local: appcode/plugins/dbconnections/Teradata.py
plugin-source: http://github.com/raw/somelocation/teradata.py 

version: 0
variables:
  some1: value
  some2: [123, 456, 789]
  some3: 123
  some4: true