host: localhost
logmech: default
encrypt: False
username: sh186014
password: "as;dlkfj"
icon: configs/Global/plugins/dbconnections/SQLite.png
plugin: SQLite.py
plugin-local: configs/Global/plugins/dbconnections
plugin-source: http://github.com/raw/somelocation/SQLite.py 

version: 0
variables:
  some1: value
  some2: [123, 456, 789]
  some3: 123
  some4: true